FROM arm64v8/ubuntu:18.04

ENV DEBIAN_FRONTEND=noninteractive

WORKDIR /xcrysden

# Install dependencies
RUN sed -i 's/archive.ubuntu.com/old-releases.ubuntu.com/g' /etc/apt/sources.list && \
    apt-get update && apt-get install -y \
    build-essential \
    gfortran \
    tcl-dev \
    tk-dev \
    libglu1-mesa-dev \
    libxmu-dev \
    libxi-dev \
    libtogl-dev \
    libfftw3-dev \
    imagemagick \
    wget \
    x11-apps \
    openbabel \
    make \
    && apt-get clean

# Download and extract source
RUN wget https://github.com/AlanSilvaaa/xcrysden-docker/raw/refs/heads/main/binary/xcrysden-arm64.tar.gz && \
    tar -xvzf xcrysden-arm64.tar.gz && \
    rm xcrysden-arm64.tar.gz

# Compile XCrySDen
WORKDIR /xcrysden/xcrysden-1.6.2

CMD ["./xcrysden"]