FROM ubuntu:18.04

WORKDIR /app

# Install dependencies for Xcrysden and python script
RUN apt-get update && \
    apt install -y tzdata && \
    ln -fs /usr/share/zoneinfo/Etc/UTC /etc/localtime && \
    dpkg-reconfigure -f noninteractive tzdata && \
    apt install -y \
    tk \
    libglu1-mesa \
    libtogl2 \
    libfftw3-3 \
    libxmu6 \
    imagemagick \
    openbabel \
    libgfortran5 \
    wget \
    git \
    python3 \
    python3-pip \
    zlib1g-dev \
    libjpeg-dev

# Install Python package
RUN pip3 install ase

# Download and extract Xcrysden
RUN wget http://www.xcrysden.org/download/xcrysden-1.6.2-linux_x86_64-shared.tar.gz

RUN tar -xf xcrysden-1.6.2-linux_x86_64-shared.tar.gz && \
    rm xcrysden-1.6.2-linux_x86_64-shared.tar.gz

# Download python script and entrypoint
RUN wget https://raw.githubusercontent.com/AlanSilvaaa/xcrysden-docker/refs/heads/main/tags/1.6.2/entrypoint.sh && \
    wget https://raw.githubusercontent.com/AlanSilvaaa/xcrysden-docker/refs/heads/main/tags/1.6.2/convert_cif_to_xsf.py

# Change working directory to the xcrysden-docker directory and copy the entrypoint script
WORKDIR /app/xcrysden-1.6.2-bin-shared
RUN chmod +x /app/entrypoint.sh

ENTRYPOINT ["/app/entrypoint.sh"]